DROP TABLE IF EXISTS sys_user;
CREATE TABLE `sys_user`(
`user_id` INT AUTO_INCREMENT,
`username` VARCHAR(255) NOT NULL,
`password` VARCHAR(255) NOT NULL,
`status` TINYINT DEFAULT 1,
`create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
`del_flag` TINYINT DEFAULT 0,
`remark` VARCHAR(255),
PRIMARY KEY (`user_id`)
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS sys_role;
CREATE TABLE `sys_role`(
`role_id` INT AUTO_INCREMENT,
`role_name` VARCHAR(255) NOT NULL,
`role_type` VARCHAR(255) NOT NULL,
`status` TINYINT DEFAULT 1,
`create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
`del_flag` TINYINT DEFAULT 0,
`remark` VARCHAR(255),
PRIMARY KEY (`role_id`)
)DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE `sys_user_role`(
`id` INT AUTO_INCREMENT,
`user_id` INT NOT NULL,
`role_id` INT NOT NULL,
`status` TINYINT DEFAULT 1,
`create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
`del_flag` TINYINT DEFAULT 0,
`remark` VARCHAR(255),
PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS sys_permission;
CREATE TABLE `sys_permission`(
`permission_id` INT AUTO_INCREMENT,
`permission_name` VARCHAR(255) NOT NULL,
`permission_type` VARCHAR(255) NOT NULL,
`status` TINYINT DEFAULT 1,
`create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
`del_flag` TINYINT DEFAULT 0,
`remark` VARCHAR(255),
PRIMARY KEY (`permission_id`)
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS sys_role_permission;
CREATE TABLE `sys_role_permission`(
`id` INT AUTO_INCREMENT,
`role_id` INT NOT NULL,
`permission_id` INT NOT NULL,
`status` TINYINT DEFAULT 1,
`create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`update_time` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
`del_flag` TINYINT DEFAULT 0,
`remark` VARCHAR(255),
PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;